In [1]:
import pandas as pd
import numpy as np
import os

files = os.listdir("../data_raw")

for file in files:
    print(file)

advance_total_manufacturing_estimates.xlsx
historical_inventories_to_shipments.xlsx
historical_new_orders.xlsx
historical_shipments.xlsx
historical_total_inventories.xlsx
historical_unfilled_orders.xlsx
historical_unfilled_orders_to_shipments.xlsx
table1_shipments_new_orders.xlsx
table2_unfilled_orders_inventory.xlsx

In [2]:
table1_path = "../data_raw/table1_shipments_new_orders.xlsx"
table2_path = "../data_raw/table2_unfilled_orders_inventory.xlsx"
advance_path = "../data_raw/advance_total_manufacturing_estimates.xlsx"

table1 = pd.read_excel(table1_path)
table2 = pd.read_excel(table2_path)
advance = pd.read_excel(advance_path)

print("Table 1 shape:", table1.shape)
print("Table 2 shape:", table2.shape)
print("Advance shape:", advance.shape)

display(table1.head(10))
display(table2.head(10))
display(advance.head(10))

Table 1 shape: (97, 14)
Table 2 shape: (97, 12)
Advance shape: (82, 13)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Table 1. Durable Goods Manufacturers' Shipmen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[Estimates are shown in millions of dollars an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Seasonally Adjusted,NaN,NaN,NaN,NaN,NaN,Not Seasonally Adjusted,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Monthly,NaN,NaN,Percent Change,NaN,NaN,Monthly,NaN,NaN,Year to Date,NaN,NaN
5,Item,NaN,,,,,,,,,,NaN,NaN,Percent
6,NaN,NaN,Mar,Feb,Jan,Feb -,Jan -,Dec -,Mar,Feb,Mar,NaN,NaN,Change
7,NaN,NaN,2026 2,2026 r,2026,Mar 2,Feb r,Jan,2026 2,2026 r,2025,2026,2025,2026/2025
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Table 2. Durable Goods Manufacturers' Unfille...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[Estimates are shown in millions of dollars an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Seasonally Adjusted,NaN,NaN,NaN,NaN,NaN,Not Seasonally Adjusted,NaN,NaN,NaN
4,NaN,NaN,Monthly,NaN,NaN,Percent Change,NaN,NaN,Monthly,NaN,NaN,Percent
5,Item,NaN,,,,,,,,,,Change
6,NaN,NaN,Mar,Feb,Jan,Feb -,Jan -,Dec -,Mar,Feb,Mar,2026/
7,NaN,NaN,2026 2,2026 r,2026,Mar 2,Feb r,Jan,2026 2,2026 r,2025,2025
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Table 1. Total Manufacturers' Shipments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[Estimates are shown in millions of dollars an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Seasonally Adjusted,NaN,NaN,NaN,NaN,NaN,Not Seasonally Adjusted,NaN,NaN,NaN,NaN
4,NaN,NaN,Monthly,NaN,NaN,Percent Change,NaN,NaN,Monthly,NaN,NaN,Percent Change,NaN
5,Industry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Mar.,Feb.,Mar,Mar./,Feb./,Mar.,Mar.,Feb.,Mar.,Mar./,Mar.
7,NaN,NaN,2026p,2026r,2025,Feb.,Jan.,2026/2025,2026p,2026r,2025,Feb.,2026/2025
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
new_orders_path = "../data_raw/historical_new_orders.xlsx"
shipments_path = "../data_raw/historical_shipments.xlsx"
unfilled_orders_path = "../data_raw/historical_unfilled_orders.xlsx"
total_inventories_path = "../data_raw/historical_total_inventories.xlsx"
inventories_to_shipments_path = "../data_raw/historical_inventories_to_shipments.xlsx"
unfilled_orders_to_shipments_path = "../data_raw/historical_unfilled_orders_to_shipments.xlsx"

In [4]:
historical_paths = [
    new_orders_path,
    shipments_path,
    unfilled_orders_path,
    total_inventories_path,
    inventories_to_shipments_path,
    unfilled_orders_to_shipments_path
]

for file_path in historical_paths:
    excel_file = pd.ExcelFile(file_path)
    print(file_path, excel_file.sheet_names)

../data_raw/historical_new_orders.xlsx ['m3-outp-nop']
../data_raw/historical_shipments.xlsx ['m3-outp-vsp']
../data_raw/historical_unfilled_orders.xlsx ['m3-outp-uop']
../data_raw/historical_total_inventories.xlsx ['m3-outp-invp']
../data_raw/historical_inventories_to_shipments.xlsx ['m3-outp-isp']
../data_raw/historical_unfilled_orders_to_shipments.xlsx ['m3-outp-usp']

In [5]:
def clean_historical_m3_file(file_path, value_name):
    raw = pd.read_excel(
        file_path,
        sheet_name=0,
        header=None
    )

    raw.columns = [
        "series_code",
        "year",
        "jan",
        "feb",
        "mar",
        "apr",
        "may",
        "jun",
        "jul",
        "aug",
        "sep",
        "oct",
        "nov",
        "dec"
    ]

    clean = raw.copy()

    clean["year"] = pd.to_numeric(clean["year"], errors="coerce")
    clean = clean.dropna(subset=["year"])
    clean["year"] = clean["year"].astype(int)

    long = clean.melt(
        id_vars=["series_code", "year"],
        value_vars=[
            "jan", "feb", "mar", "apr", "may", "jun",
            "jul", "aug", "sep", "oct", "nov", "dec"
        ],
        var_name="month",
        value_name=value_name
    )

    month_map = {
        "jan": 1,
        "feb": 2,
        "mar": 3,
        "apr": 4,
        "may": 5,
        "jun": 6,
        "jul": 7,
        "aug": 8,
        "sep": 9,
        "oct": 10,
        "nov": 11,
        "dec": 12
    }

    long["month_num"] = long["month"].map(month_map)

    long["date"] = pd.to_datetime(
        dict(
            year=long["year"],
            month=long["month_num"],
            day=1
        )
    )

    long[value_name] = pd.to_numeric(long[value_name], errors="coerce")

    long = long[
        ["series_code", "date", "year", "month_num", value_name]
    ]

    return long

In [6]:
new_orders_clean = clean_historical_m3_file(
    new_orders_path,
    "new_orders"
)

shipments_clean = clean_historical_m3_file(
    shipments_path,
    "shipments"
)

unfilled_orders_clean = clean_historical_m3_file(
    unfilled_orders_path,
    "unfilled_orders"
)

total_inventories_clean = clean_historical_m3_file(
    total_inventories_path,
    "total_inventories"
)

inventories_to_shipments_clean = clean_historical_m3_file(
    inventories_to_shipments_path,
    "inventories_to_shipments"
)

unfilled_orders_to_shipments_clean = clean_historical_m3_file(
    unfilled_orders_to_shipments_path,
    "unfilled_orders_to_shipments"
)

display(new_orders_clean.head())
display(shipments_clean.head())
display(unfilled_orders_clean.head())

print("New Orders:", new_orders_clean.shape)
print("Shipments:", shipments_clean.shape)
print("Unfilled Orders:", unfilled_orders_clean.shape)
print("Total Inventories:", total_inventories_clean.shape)
print("Inventories to Shipments:", inventories_to_shipments_clean.shape)
print("Unfilled Orders to Shipments:", unfilled_orders_to_shipments_clean.shape)

  series_code       date  year  month_num  new_orders
0      AMTMNO 1992-01-01  1992          1         NaN
1      AMTMNO 1993-01-01  1993          1    239924.0
2      AMTMNO 1994-01-01  1994          1    257125.0
3      AMTMNO 1995-01-01  1995          1    279692.0
4      AMTMNO 1996-01-01  1996          1    285822.0

  series_code       date  year  month_num  shipments
0      AMTMVS 1992-01-01  1992          1   227721.0
1      AMTMVS 1993-01-01  1993          1   247812.0
2      AMTMVS 1994-01-01  1994          1   259834.0
3      AMTMVS 1995-01-01  1995          1   286480.0
4      AMTMVS 1996-01-01  1996          1   286897.0

  series_code       date  year  month_num  unfilled_orders
0      AMTMUO 1992-01-01  1992          1         471297.0
1      AMTMUO 1993-01-01  1993          1         445479.0
2      AMTMUO 1994-01-01  1994          1         426329.0
3      AMTMUO 1995-01-01  1995          1         432805.0
4      AMTMUO 1996-01-01  1996          1         452372.0

New Orders: (43680, 5)
Shipments: (72696, 5)
Unfilled Orders: (42000, 5)
Total Inventories: (132720, 5)
Inventories to Shipments: (20160, 5)
Unfilled Orders to Shipments: (7560, 5)

In [7]:
new_orders_clean.to_csv("../data_cleaned/new_orders_cleaned.csv", index=False)
shipments_clean.to_csv("../data_cleaned/shipments_cleaned.csv", index=False)
unfilled_orders_clean.to_csv("../data_cleaned/unfilled_orders_cleaned.csv", index=False)
total_inventories_clean.to_csv("../data_cleaned/total_inventories_cleaned.csv", index=False)
inventories_to_shipments_clean.to_csv("../data_cleaned/inventories_to_shipments_cleaned.csv", index=False)
unfilled_orders_to_shipments_clean.to_csv("../data_cleaned/unfilled_orders_to_shipments_cleaned.csv", index=False)

print("All cleaned CSV files saved.")

All cleaned CSV files saved.

In [8]:
cleaned_files = os.listdir("../data_cleaned")

for file in cleaned_files:
    print(file)

inventories_to_shipments_cleaned.csv
m3_master_supply_chain_dataset.csv
m3_master_with_kpis.csv
new_orders_cleaned.csv
shipments_cleaned.csv
total_inventories_cleaned.csv
unfilled_orders_cleaned.csv
unfilled_orders_to_shipments_cleaned.csv

In [9]:
# Load cleaned files
new_orders = pd.read_csv("../data_cleaned/new_orders_cleaned.csv")
shipments = pd.read_csv("../data_cleaned/shipments_cleaned.csv")
unfilled_orders = pd.read_csv("../data_cleaned/unfilled_orders_cleaned.csv")
total_inventories = pd.read_csv("../data_cleaned/total_inventories_cleaned.csv")
inventories_to_shipments = pd.read_csv("../data_cleaned/inventories_to_shipments_cleaned.csv")
unfilled_orders_to_shipments = pd.read_csv("../data_cleaned/unfilled_orders_to_shipments_cleaned.csv")

# Merge all datasets together
master = new_orders.merge(
    shipments,
    on=["series_code", "date", "year", "month_num"],
    how="left"
)

master = master.merge(
    unfilled_orders,
    on=["series_code", "date", "year", "month_num"],
    how="left"
)

master = master.merge(
    total_inventories,
    on=["series_code", "date", "year", "month_num"],
    how="left"
)

master = master.merge(
    inventories_to_shipments,
    on=["series_code", "date", "year", "month_num"],
    how="left"
)

master = master.merge(
    unfilled_orders_to_shipments,
    on=["series_code", "date", "year", "month_num"],
    how="left"
)

# Convert date column back to datetime
master["date"] = pd.to_datetime(master["date"])

display(master.head())
display(master.tail())
print(master.shape)
print(master.columns)

,series_code,date,year,month_num,new_orders,shipments,unfilled_orders,total_inventories,inventories_to_shipments,unfilled_orders_to_shipments
0,AMTMNO,1992-01-01,1992,1,NaN,NaN,NaN,NaN,NaN,NaN
1,AMTMNO,1993-01-01,1993,1,239924.0,NaN,NaN,NaN,NaN,NaN
2,AMTMNO,1994-01-01,1994,1,257125.0,NaN,NaN,NaN,NaN,NaN
3,AMTMNO,1995-01-01,1995,1,279692.0,NaN,NaN,NaN,NaN,NaN
4,AMTMNO,1996-01-01,1996,1,285822.0,NaN,NaN,NaN,NaN,NaN

,series_code,date,year,month_num,new_orders,shipments,unfilled_orders,total_inventories,inventories_to_shipments,unfilled_orders_to_shipments
43675,UODGNO,2022-12-01,2022,12,46092.0,NaN,NaN,NaN,NaN,NaN
43676,UODGNO,2023-12-01,2023,12,45489.0,NaN,NaN,NaN,NaN,NaN
43677,UODGNO,2024-12-01,2024,12,46308.0,NaN,NaN,NaN,NaN,NaN
43678,UODGNO,2025-12-01,2025,12,47560.0,NaN,NaN,NaN,NaN,NaN
43679,UODGNO,2026-12-01,2026,12,NaN,NaN,NaN,NaN,NaN,NaN

(43680, 10)
Index(['series_code', 'date', 'year', 'month_num', 'new_orders', 'shipments',
       'unfilled_orders', 'total_inventories', 'inventories_to_shipments',
       'unfilled_orders_to_shipments'],
      dtype='str')

In [10]:
master.to_csv("../data_cleaned/m3_master_supply_chain_dataset.csv", index=False)

print("Master dataset saved.")

Master dataset saved.